apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: vehicles-api
    app.kubernetes.io/component: vehicles-api
  name: vehicles-api
spec:
  lookupPolicy:
    local: false
